### ISSUE TITLE
Segfault in lime.ndll

### ISSUE THREAD

**Issue by wvxvw** [jcward/hxScout#39] opened 2015-01-27 10:34 UTC
Is it possible it's a version mismatch? If so, what version do I need? Below is the GDB output that points at `nme::TextField::SplitGroup(int, int)` as the source of the problem:

```
gdb ./hxScoutSplash 
GNU gdb (GDB) Fedora 7.6.1-46.fc19
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/wvxvw/bin/hxScoutSplash...(no debugging symbols found)...done.
(gdb) c
The program is not being run.
(gdb) r
Starting program: /home/wvxvw/bin/./hxScoutSplash 
warning: the debug information found in "/usr/lib/debug//lib64/ld-2.17.so.debug" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libpthread-2.17.so.debug" does not match "/lib64/libpthread.so.0" (CRC mismatch).

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//lib64/libdl-2.17.so.debug" does not match "/lib64/libdl.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libstdc++.so.6.0.19.debug" does not match "/lib64/libstdc++.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libstdc++.so.6.0.19.debug" does not match "/lib64/libstdc++.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64//libstdc++.so.6.0.19.debug" does not match "/lib64/libstdc++.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libm-2.17.so.debug" does not match "/lib64/libm.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.17.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

[New Thread 0x7ffff7fcc700 (LWP 13233)]
[New Thread 0x7ffff777b700 (LWP 13234)]
[New Thread 0x7ffff6f2a700 (LWP 13235)]
[New Thread 0x7ffff66d9700 (LWP 13236)]
warning: the debug information found in "/usr/lib/debug//lib64/librt-2.17.so.debug" does not match "/lib64/librt.so.1" (CRC mismatch).

[New Thread 0x7ffff5070700 (LWP 13237)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5525a49 in nme::TextField::SplitGroup(int, int) () from ././lime.ndll
Missing separate debuginfos, use: debuginfo-install glibc-2.17-21.fc19.x86_64 libgcc-4.8.3-1.fc19.x86_64 libstdc++-4.8.3-1.fc19.x86_64
(gdb) q
```

As a side-note, could you please put a more detalied usage instructions? `hxScoutMain` starts and even displays some GUI, but does nothing. SWFs, even the one I donloaded from http://hxscout.com/test_profalloc.swf don't seem to ever connect to the server (if I just ping it with `nc` it responds). What purpose does `hxScoutSplash` serve?

**Comment by jcward** [comment] 2015-01-28 04:56
hxScoutSplash is simply a splash screen. I'm not really happy with the way it turned out, so I'll likely remove it in the next release.  See issue #30.

If you're getting nothing in hxScout when a SWF starts (but sending data with `nc` works), it's likely that somethings wrong with your `.telemetry.cfg` setup.  See this [Adobe article](http://www.adobe.com/devnet/scout/articles/adobe-scout-getting-started.html#articlecontentAdobe_text_9) for details on Win and Mac. If you're on Linux, however, getting telemetry output is more difficult. See my notes [here](https://forums.adobe.com/message/7088405#7088405) and [here](https://bugbase.adobe.com/index.cfm?event=bug&id=3916760).

More detailed usage info is on the todo list.  =D But the project is very young and still highly in flux.

I'll close this issue as a duplicate of #30, though I believe it'll be resolved when I remove the separate Splash project.

**Closed by jcward** 2015-01-28 04:56 UTC
